### ISSUE TITLE
adapting to GCN surface height records

### ISSUE THREAD

**Issue by jasonebox** [GEUS-PROMICE/PROMICE-AWS-toolbox#2]
For GCN planning purposes, the tools are useful to apply to be able to estimate how buried not-transmitting stations* will be. *NASA-SE, South Dome, GITS and Crawford Pt. 1. 

I'd be interested in trying to apply your toolchain. I have some time this week. It would be faster, of course, if you did. But I'm interested in learning.

Jason

**Comment by BaptisteVandecrux** [comment]
Using data prepared in https://doi.org/10.1017/jog.2020.30
Here are the average and standard deviation of the annual surface height change seen by the stations:
CP1 0.89 +/- 0.42 m yr-1
DYE_2 0.67 +/- 0.35 m yr-1
NASA_E 0.36 +/- 0.2 m yr-1
NASA_SE 1.3 +/- 0.45 m yr-1
NASA_U 0.76 +/- 0.26 m yr-1
Saddle 0.9 +/- 0.33 m yr-1
SouthDome 1.29 +/- 0.27 m yr-1
Summit 0.47 +/- 0.16 m yr-1
TUNU_N 0.31 +/- 0.18 m yr-1

![image](https://user-images.githubusercontent.com/35140661/104580685-d9259c00-565d-11eb-8698-9dfe9e4027ca.png)
